[lsrun]
env_path = "C:\\Program Files\\ANSYS Inc\\v221\\ansys\\bin\\winx64\\lsprepost47\\lsdynamsvar.bat"
bin_path = "C:\\Program Files\\ANSYS Inc\\v221\\ansys\\bin\\winx64\\lsdyna_mpp_sp_msmpi.exe"
job_path = "C:\\Users\\ADMIN\\Desktop\\dyna\\run.key"

[param]
# now we use real number
name = "tsteel"
# initial value is the one written in key file, however you need to define 2 boundary here
paras =[2,2.5,3,3.5,4]
