[[parts]]
name = "polo"
mat = "steel"

[[parts]]
name = "car"
mat = "steel"

[[node_sets]]
name = "fixd"
[[node_sets]]
name = "car"

[[parts]]
name = "soil"
#default goes to part name, e.g. `mat = "soil"`

